# Generated by Django 5.0.2 on 2024-09-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'videos'},
        ),
    ]
