# Generated by Django 5.1.3 on 2024-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_usuario_options_remove_usuario_senha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='genero',
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ManyToManyField(related_name='filmes', to='app.categoria'),
        ),
        migrations.AddField(
            model_name='serie',
            name='genero',
            field=models.ManyToManyField(related_name='series', to='app.categoria'),
        ),
    ]
