# Generated by Django 5.1.4 on 2024-12-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_usuario_email_alter_usuario_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='plano_assinatura',
            field=models.CharField(max_length=50),
        ),
    ]
